Hash code
TouchInstinct/RoboSwag-core pull request #17
Opened 2017-02-13 16:07 UTC by ZuZuK

2017-02-14 01:07 UTC, seva-ask requested changes

2017-02-14 01:07 UTC, seva-ask commented on src/main/java/ru/touchin/roboswag/core/utils/ObjectUtils.java
> +                && map1.entrySet().containsAll(map2.entrySet());
еще в обратную сторону не хватает проверки, сейчас ты только на вхождение проверяешь

2017-02-16 17:29 UTC, seva-ask commented on src/main/java/ru/touchin/roboswag/core/utils/ObjectUtils.java
> +        return map1 == map2 || !(map1 == null || map2 == null)
подозреваю, что первую строчку можно заменить кодом из либы

2017-02-17 12:20 UTC, ZuZuK commented on src/main/java/ru/touchin/roboswag/core/utils/ObjectUtils.java
> +        return map1 == map2 || !(map1 == null || map2 == null)
тогда придется на нулы все равно  проверять, так как там стоит аннотация Nullable. просто строчка map1 == map2 заменится на ObjectUtils.equals(map1, map2) - а там опять будут проверки на нулы. не хочу этого

2017-02-17 15:29 UTC, seva-ask approved these changes

2017-02-17 15:29 UTC, merged